export const UserViewTypes = {
  GET_USER_VIEW_REQUEST: 'GET_USER_VIEW_REQUEST',
  GET_USER_VIEW_SUCCESS: 'GET_USER_VIEW_SUCCESS',
  GET_USER_VIEW_ERROR: 'GET_USER_VIEW_ERROR',

  EDIT_USER_VIEW_REQUEST: 'EDIT_USER_VIEW_REQUEST',
  EDIT_USER_VIEW_SUCCESS: 'EDIT_USER_VIEW_SUCCESS',
  EDIT_USER_VIEW_ERROR: 'EDIT_USER_VIEW_ERROR',
};
