export const MediaViewTypes = {
  GET_MEDIA_VIEW_REQUEST: 'GET_MEDIA_VIEW_REQUEST',
  GET_MEDIA_VIEW_SUCCESS: 'GET_MEDIA_VIEW_SUCCESS',
  GET_MEDIA_VIEW_ERROR: 'GET_MEDIA_VIEW_ERROR',

  EDIT_MEDIA_VIEW_REQUEST: 'EDIT_MEDIA_VIEW_REQUEST',
  EDIT_MEDIA_VIEW_SUCCESS: 'EDIT_MEDIA_VIEW_SUCCESS',
  EDIT_MEDIA_VIEW_ERROR: 'EDIT_MEDIA_VIEW_ERROR',

  EDIT_MEDIA_VIEW_RESET: 'EDIT_MEDIA_VIEW_RESET',

  DELETE_MEDIA_VIEW_REQUEST: 'DELETE_MEDIA_VIEW_REQUEST',
  DELETE_MEDIA_VIEW_SUCCESS: 'DELETE_MEDIA_VIEW_SUCCESS',
  DELETE_MEDIA_VIEW_ERROR: 'DELETE_MEDIA_VIEW_ERROR',
};
