export const SearchTypes = {
  GET_SEARCH_MEME_REQUEST: 'GET_SEARCH_MEME_REQUEST',
  GET_SEARCH_MEME_SUCCESS: 'GET_SEARCH_MEME_SUCCESS',
  GET_SEARCH_MEME_ERROR: 'GET_SEARCH_MEME_ERROR',

  GET_SEARCH_GIF_REQUEST: 'GET_SEARCH_GIF_REQUEST',
  GET_SEARCH_GIF_SUCCESS: 'GET_SEARCH_GIF_SUCCESS',
  GET_SEARCH_GIF_ERROR: 'GET_SEARCH_GIF_ERROR',

  GET_SEARCH_USER_REQUEST: 'GET_SEARCH_USER_REQUEST',
  GET_SEARCH_USER_SUCCESS: 'GET_SEARCH_USER_SUCCESS',
  GET_SEARCH_USER_ERROR: 'GET_SEARCH_USER_ERROR',

  SEARCH_FILTER_MEME_CHANGE: 'SEARCH_FILTER_MEME_CHANGE',
  SEARCH_FILTER_GIF_CHANGE: 'SEARCH_FILTER_GIF_CHANGE',
  SEARCH_FILTER_USER_CHANGE: 'SEARCH_FILTER_USER_CHANGE',
};
