export const AuthTypes = {
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',

  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_ERROR: 'SIGN_OUT_ERROR',

  SEND_PASSWORD_RESET_EMAIL_REQUEST: 'SEND_PASSWORD_RESET_EMAIL_REQUEST',
  SEND_PASSWORD_RESET_EMAIL_ERROR: 'SEND_PASSWORD_RESET_EMAIL_ERROR',
  SEND_PASSWORD_RESET_EMAIL_SUCCESS: 'SEND_PASSWORD_RESET_EMAIL_SUCCESS',

  RESET_AUTH_STATE: 'RESET_AUTH_STATE',
};
